Client/Controllers/EnrollController.cs
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Reflection;

namespace Client.Controllers
{
    public class EnrollController : Controller
    {
        private readonly HttpClient _client;

        public EnrollController()
        {
            _client = new HttpClient();
        }

        public IActionResult Index(int id)
        {
            List<Course> courseById = new List<Course>();
            Course c = null;
            HttpResponseMessage response1 = _client.GetAsync("https://localhost:7078/api/Course?$filter=courseId eq " + id).Result;
            if (response1.IsSuccessStatusCode)
            {
                string data = response1.Content.ReadAsStringAsync().Result;
                courseById = JsonConvert.DeserializeObject<List<Course>>(data);
                if (courseById.Count>0)
                {
                    c = courseById[0];
                }
            }
            if (c != null)
            {
                HttpResponseMessage response = _client.GetAsync("https://localhost:7078/api/Course/CourseCategory?$filter=categoryId eq " + c.CategoryId).Result;
                if(response.IsSuccessStatusCode)
                {
                    string dt = response.Content.ReadAsStringAsync().Result;
                    List<CourseCategory> ctg = JsonConvert.DeserializeObject<List<CourseCategory>>(dt);
                    ViewData["CategoryName"] = ctg[0].CategoryName;
                }
            }
            return View(c);
        }
        [HttpPost]
        public IActionResult SubmitEnroll(string courseId)
        {
            string uid = HttpContext.Request.Cookies["loginId"];

            //Course c1 = null;
            //User u1 = null;
            //List<Course> courses = null;
            //HttpResponseMessage response1 = _client.GetAsync("https://localhost:7078/api/Course?$filter=courseId eq " + courseId).Result;
            //if (response1.IsSuccessStatusCode)
            //{
            //    string c = response1.Content.ReadAsStringAsync().Result;
            //    courses = JsonConvert.DeserializeObject<List<Course>>(c);
            //    if (courses.Count > 0)
            //    {
            //        c1 = courses[0];
            //    }
            //}

            //List<User> users = null;
            //HttpResponseMessage response2 = _client.GetAsync("https://localhost:7078/api/Course?$filter=courseId eq " + courseId).Result;
            //if (response2.IsSuccessStatusCode)
            //{
            //    string u = response2.Content.ReadAsStringAsync().Result;
            //    users = JsonConvert.DeserializeObject<List<User>>(u);
            //    if (users.Count > 0)
            //    {
            //        u1 = users[0];
            //    }
            //}

            Enrollment enrollment = new Enrollment();
            enrollment.EnrollTime = DateTime.Now;
            enrollment.CourseId = int.Parse(courseId);
            enrollment.UserId = int.Parse(uid);
            //enrollment.Course = c1;
            //enrollment.User = u1;

            string data = JsonConvert.SerializeObject(enrollment);
            var content = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
            HttpResponseMessage response = _client.PostAsync("https://localhost:7078/api/Enroll", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "WeekLesson", new { id = courseId });
            }
            return View();
        }
    }
}

Client/Views/Enroll/Index.cshtml
@using Client.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Course
<!DOCTYPE html>
<html dir="ltr" lang="vi" xml:lang="vi" class="yui3-js-enabled">

<head>
    <title>CMS - Course Management System</title>
    <link rel="shortcut icon" href="https://cmshn.fpt.edu.vn/theme/image.php/trema/theme/1692173377/favicon">
    <meta name="apple-itunes-app" content="app-id=633359593, app-argument=https://cmshn.fpt.edu.vn/">
    <link rel="manifest" href="https://cmshn.fpt.edu.vn/admin/tool/mobile/mobile.webmanifest.php">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content="moodle, CMS - Course Management System">
    <link rel="stylesheet" type="text/css"
          href="https://cmshn.fpt.edu.vn/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.css">
    <script charset="utf-8" id="yui_3_17_2_1_1696445272916_8"
            src="https://cmshn.fpt.edu.vn/theme/yui_combo.php?m/1566968257/core/event/event-min.js&amp;m/1566968257/filter_mathjaxloader/loader/loader-min.js"
            async=""></script>
    <script charset="utf-8" id="yui_3_17_2_1_1696445272916_18"
            src="https://cmshn.fpt.edu.vn/theme/yui_combo.php?3.17.2/event-mousewheel/event-mousewheel-min.js&amp;3.17.2/event-resize/event-resize-min.js&amp;3.17.2/event-hover/event-hover-min.js&amp;3.17.2/event-touch/event-touch-min.js&amp;3.17.2/event-move/event-move-min.js&amp;3.17.2/event-flick/event-flick-min.js&amp;3.17.2/event-valuechange/event-valuechange-min.js&amp;3.17.2/event-tap/event-tap-min.js"
            async=""></script>
    <script charset="utf-8" id="yui_3_17_2_2_1696445272916_2"
            src="https://cmshn.fpt.edu.vn/theme/yui_combo.php?3.17.2/datatype-xml-parse/datatype-xml-parse-min.js&amp;3.17.2/io-xdr/io-xdr-min.js&amp;3.17.2/io-form/io-form-min.js&amp;3.17.2/io-upload-iframe/io-upload-iframe-min.js&amp;3.17.2/queue-promote/queue-promote-min.js&amp;3.17.2/io-queue/io-queue-min.js"
            async=""></script>
    <script id="firstthemesheet"
            type="text/css">/** Required in order to fix style inclusion problems in IE with YUI **/</script>
    <link rel="stylesheet" type="text/css" href="https://cmshn.fpt.edu.vn/theme/styles.php/trema/1692173377_1/all">
    <meta name="description" content="Course Management System">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="core/first"
            src="https://cmshn.fpt.edu.vn/lib/requirejs.php/1566968257/core/first.js"></script>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            config: ["Accessible.js", "Safe.js"],
            errorSettings: { message: ["!"] },
            skipStartupTypeset: true,
            messageStyle: "none"
        });
    </script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="jquery"
            src="https://cmshn.fpt.edu.vn/lib/javascript.php/1566968257/lib/jquery/jquery-3.2.1.min.js"></script>
</head>

<body id="page-site-index"
      class="format-site course path-site chrome android dir-ltr lang-vi yui-skin-sam yui3-skin-sam cmshn-fpt-edu-vn pagelayout-frontpage course-1 context-2 notloggedin mobiletheme jsenabled drawer-ease">

    <div id="page-wrapper">
        <div>
            <a class="sr-only sr-only-focusable" href="#maincontent">Chuyển tới nội dung chính</a>
        </div>
        <script type="text/javascript"
                src="https://cmshn.fpt.edu.vn/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js"></script>
        <script type="text/javascript"
                src="https://cmshn.fpt.edu.vn/lib/javascript.php/1566968257/lib/javascript-static.js"></script>
        <script type="text/javascript">
            document.body.className += ' jsenabled';
        </script>



        <nav class="fixed-top navbar navbar-light bg-white navbar-expand moodle-has-zindex"
             id="yui_3_17_2_1_1696445272916_19">


            <a href="https://cmshn.fpt.edu.vn" class="navbar-brand has-logo">
                <span class="logo d-inline">
                    <img src="https://cmshn.fpt.edu.vn/pluginfile.php/1/core_admin/logocompact/0x70/1692173377/2020-FPTU-Eng.png"
                         alt="eLearning">
                </span>
            </a>

            <ul class="navbar-nav d-none d-md-flex">
            </ul>
            <ul class="nav navbar-nav ml-auto" id="yui_3_17_2_1_1696445272916_25">
                <li class="nav-item">

                </li>
            </ul>
        </nav>
        <div id="page" class="container-fluid">
            <h2>@Model.Name - @ViewData["CategoryName"]</h2>

            <div class="row card-deck mb-4" style="margin-top: 20px">
                <div style="background-color: rgb(244, 244, 236);" class="mb-4">
                    <img style="height: 200px; width: 400px;"
                         src="https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&q=80&w=2029&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"></img>
                    <div style="text-align: center;" class="card-body">
                        <p>@Model.Name</p>
                        <p>@Model.Code</p>
                    </div>
                </div>
                <div>
                    <form method="post" asp-action="SubmitEnroll" asp-controller="Enroll">
                        <input 
                               name="courseId" value="@Model.CourseId" hidden >
                        <button type="submit" style="padding-top: 0; margin-top: 0;" class="btn btn-primary ">Enroll me</button>
                    </form>
                    
                </div>

            </div>
        </div>



    </div>


    </div>
</body>

</html>