Client/Models/WeekLesson.cs
using System;
using System.Collections.Generic;

namespace Client.Models
{
    public partial class WeekLesson
    {
        public WeekLesson()
        {
            Assignments = new HashSet<Assignment>();
        }

        public int Id { get; set; }
        public int? CourseId { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? StartDate { get; set; }

        public virtual Course? Course { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
    }
}

Client/Controllers/WeekLessonController.cs
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Client.Controllers
{
    public class WeekLessonController : Controller
    {
        private readonly HttpClient _client;

        public WeekLessonController()
        {
            _client = new HttpClient();
        }
        public IActionResult Index(int id)
        {
            List<Course> courseById = new List<Course>();
            Course c = null;
            HttpResponseMessage response1 = _client.GetAsync("https://localhost:7078/api/Course?$filter=courseId eq " + id).Result;
            if (response1.IsSuccessStatusCode)
            {
                string data = response1.Content.ReadAsStringAsync().Result;
                courseById = JsonConvert.DeserializeObject<List<Course>>(data);
                if (courseById.Count > 0)
                {
                    c = courseById[0];
                }
            }
            if (c != null)
            {
                HttpResponseMessage response = _client.GetAsync("https://localhost:7078/api/WeekLesson?$filter=courseId eq " + id).Result;
                if (response.IsSuccessStatusCode)
                {
                    string dt = response.Content.ReadAsStringAsync().Result;
                    List<WeekLesson> ctg = JsonConvert.DeserializeObject<List<WeekLesson>>(dt);
                    ViewBag.weeklesson = ctg;
                }
            }
            return View(c);
        }
        public IActionResult Unenroll(int courseId)
        {
            string uid = HttpContext.Request.Cookies["loginId"];
            HttpResponseMessage response1 = _client.DeleteAsync("https://localhost:7078/api/Enroll?uid="+uid+"&cid="+ courseId).Result;
            if (response1.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Course");
            }
           
            return RedirectToAction("Index");
        }
    }
}

Client/Views/WeekLesson/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Client.Models;
@model Course
@{
    var weeklesson = ViewBag.weeklesson as List<WeekLesson>;
}
<!DOCTYPE html>
<html dir="ltr" lang="vi" xml:lang="vi" class="yui3-js-enabled">

<head>
    <title>CMS - Course Management System</title>
    <link rel="shortcut icon" href="https://cmshn.fpt.edu.vn/theme/image.php/trema/theme/1692173377/favicon">
    <meta name="apple-itunes-app" content="app-id=633359593, app-argument=https://cmshn.fpt.edu.vn/">
    <link rel="manifest" href="https://cmshn.fpt.edu.vn/admin/tool/mobile/mobile.webmanifest.php">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content="moodle, CMS - Course Management System">
    <link rel="stylesheet" type="text/css"
          href="https://cmshn.fpt.edu.vn/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.css">
    <script charset="utf-8" id="yui_3_17_2_1_1696445272916_8"
            src="https://cmshn.fpt.edu.vn/theme/yui_combo.php?m/1566968257/core/event/event-min.js&amp;m/1566968257/filter_mathjaxloader/loader/loader-min.js"
            async=""></script>
    <script charset="utf-8" id="yui_3_17_2_1_1696445272916_18"
            src="https://cmshn.fpt.edu.vn/theme/yui_combo.php?3.17.2/event-mousewheel/event-mousewheel-min.js&amp;3.17.2/event-resize/event-resize-min.js&amp;3.17.2/event-hover/event-hover-min.js&amp;3.17.2/event-touch/event-touch-min.js&amp;3.17.2/event-move/event-move-min.js&amp;3.17.2/event-flick/event-flick-min.js&amp;3.17.2/event-valuechange/event-valuechange-min.js&amp;3.17.2/event-tap/event-tap-min.js"
            async=""></script>
    <script charset="utf-8" id="yui_3_17_2_2_1696445272916_2"
            src="https://cmshn.fpt.edu.vn/theme/yui_combo.php?3.17.2/datatype-xml-parse/datatype-xml-parse-min.js&amp;3.17.2/io-xdr/io-xdr-min.js&amp;3.17.2/io-form/io-form-min.js&amp;3.17.2/io-upload-iframe/io-upload-iframe-min.js&amp;3.17.2/queue-promote/queue-promote-min.js&amp;3.17.2/io-queue/io-queue-min.js"
            async=""></script>
    <script id="firstthemesheet"
            type="text/css">/** Required in order to fix style inclusion problems in IE with YUI **/</script>
    <link rel="stylesheet" type="text/css" href="https://cmshn.fpt.edu.vn/theme/styles.php/trema/1692173377_1/all">
    <meta name="description" content="Course Management System">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="core/first"
            src="https://cmshn.fpt.edu.vn/lib/requirejs.php/1566968257/core/first.js"></script>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            config: ["Accessible.js", "Safe.js"],
            errorSettings: { message: ["!"] },
            skipStartupTypeset: true,
            messageStyle: "none"
        });
    </script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="jquery"
            src="https://cmshn.fpt.edu.vn/lib/javascript.php/1566968257/lib/jquery/jquery-3.2.1.min.js"></script>
</head>

<body id="page-site-index"
      class="format-site course path-site chrome android dir-ltr lang-vi yui-skin-sam yui3-skin-sam cmshn-fpt-edu-vn pagelayout-frontpage course-1 context-2 notloggedin mobiletheme jsenabled drawer-ease">

    <div id="page-wrapper">
        <div>
            <a class="sr-only sr-only-focusable" href="#maincontent">Chuyển tới nội dung chính</a>
        </div>
        <script type="text/javascript"
                src="https://cmshn.fpt.edu.vn/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js"></script>
        <script type="text/javascript"
                src="https://cmshn.fpt.edu.vn/lib/javascript.php/1566968257/lib/javascript-static.js"></script>
        <script type="text/javascript">
            document.body.className += ' jsenabled';
        </script>
        <nav class="fixed-top navbar navbar-light bg-white navbar-expand moodle-has-zindex"
             id="yui_3_17_2_1_1696445272916_19">


            <a href="https://cmshn.fpt.edu.vn" class="navbar-brand has-logo">
                <span class="logo d-inline">
                    <img src="https://cmshn.fpt.edu.vn/pluginfile.php/1/core_admin/logocompact/0x70/1692173377/2020-FPTU-Eng.png"
                         alt="eLearning">
                </span>
            </a>

            <ul class="navbar-nav d-none d-md-flex">
            </ul>
            <ul class="nav navbar-nav ml-auto" id="yui_3_17_2_1_1696445272916_25">
                <li class="nav-item">

                </li>
            </ul>
        </nav>
        <div id="page" class="container-fluid">
            <header style="margin: 20px;" id="page-header" class="row">
                <div class="col-12 pt-3 pb-3">
                    <div class="card ">
                        <div class="card-body ">
                            <div class="d-flex">
                                <div class="mr-auto">
                                    <div class="page-context-header">
                                        <div class="page-header-headings">
                                            <h1>@Model.Name</h1>
                                        </div>
                                    </div>
                                </div>
                                <div class="context-header-settings-menu">
                                    <div class="action-menu moodle-actionmenu d-inline" id="action-menu-2"
                                         data-enhance="moodle-core-actionmenu">

                                        <div class="menubar d-flex " id="action-menu-2-menubar" role="menubar">
                                            <div class="action-menu-trigger">
                                                <form asp-action="Unenroll" asp-controller="WeekLesson">
                                                    <input name="courseId" value="@Model.CourseId" hidden>
                                                    <button type="submit" style="padding-top: 0; margin-top: 0;" >Unenroll</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                    </div>

                </div>
            </header>

            <div id="page-content" class="row">
                <div id="region-main-box" class="col-12">
                    <section id="region-main">
                        <div class="card">
                            <div class="card-body" style="background-color: white;">
                                <span class="notifications" id="user-notifications"></span>
                                <div role="main">
                                    <div class="course-content">
                                        <h2 class="accesshide">Weekly outline</h2>
                                        <ul class="weeks">
                                            <li id="section-0" class="section main clearfix" role="region"
                                                aria-label="General">
                                                <span class="hidden sectionname">General</span>
                                                <div class="left side"></div>
                                                <div class="right side">
                                                    <img class="icon spacer" width="1" height="1"
                                                         alt="" aria-hidden="true"
                                                         src="https://cmshn.fpt.edu.vn/theme/image.php/trema/core/1697438386/spacer">
                                                </div>
                                                <div class="content">

                                                    <ul class="section img-text">
                                                        <li class="activity forum modtype_forum " id="module-134734">
                                                            <div>
                                                                <div class="mod-indent-outer">
                                                                    <div class="mod-indent"></div>
                                                                    <div>
                                                                        <div class="activityinstance">
                                                                            <a class=""
                                                                               onclick=""
                                                                               href="https://cmshn.fpt.edu.vn/mod/forum/view.php?id=134734">
                                                                                <img src="https://cmshn.fpt.edu.vn/theme/image.php/trema/forum/1697438386/icon"
                                                                                     class="iconlarge activityicon"
                                                                                     alt="" role="presentation"
                                                                                     aria-hidden="true"><span class="instancename">
                                                                                    Announcements<span class="accesshide ">
                                                                                        Forum
                                                                                    </span>
                                                                                </span>
                                                                            </a>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </ul>

                                            </li>
                                            <li id="section-1" class="section main section-summary clearfix"
                                                role="region" aria-label="4 September - 10 September">
                                                <div class="left side"></div>
                                                <div class="right side"></div>
                                                <div class="content">
                                                    <h3 class="section-title">
                                                        <a href="https://cmshn.fpt.edu.vn/course/view.php?id=4267&amp;section=1"
                                                           class="">4 September - 10 September</a>
                                                    </h3>
                                                    <div class="section_availability"></div>
                                                    <div class="summarytext"></div>
                                                    <div class="section-summary-activities mdl-right">
                                                        <span class="activity-count">File: 1</span>
                                                    </div>
                                                    <div class="section-summary-activities mdl-right">
                                                        <span class="activity-count">Progress: 1 / 1</span>
                                                    </div>
                                                </div>
                                            </li>

                                        </ul>
                                    </div>
                                </div>


                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>
</body>

</html>